apiVersion: v1
kind: Service
metadata:
  name: app-apache
  labels:
    app: app-apache
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app-apache
    tier: app-apache
  type: LoadBalancer